### ISSUE TITLE
video information display

### ISSUE THREAD

**Issue by dylanjedwards** [jilliangmeehan/dylan-edwards#27]
need to figure out information display for each video, whether that can be adjusted on the actual embed "screen" or we have it on the far right side and it fades in and out depending on the video

im open to both, and am leaning towards the second

**Comment by jilliangmeehan** [comment]
can you be more specific about what you want it to look like in either case? if you want to see the caption only while the video is playing, i can probably make some adjustments to how it is now. if you want to see it only when you hover over the thumbnail or something i can do that instead, it'll just be more work.

**Comment by dylanjedwards** [comment]
![Screen Shot 2020-07-23 at 12 51 11 PM](https://user-images.githubusercontent.com/55369380/88315035-cd2ad400-cce3-11ea-947f-0d046ed764d7.jpg)

I think I'm leaning towards something like this, whatever is easier. If you want it to be where it's a hover action we can try, or just whenever you scroll it fades in and out depending on the project currently displayed

**Comment by jilliangmeehan** [comment]
definitely can do that, it'll just be more work. do you not want to have the caption on the video at all in this case?

**Comment by dylanjedwards** [comment]
I think we don't need the caption for the video, it'll be too difficult I think on your end to get it how I'd like it and be comfortable, especially with all the dif screen sizes possible, so this seems like it'd be the simplest. is it hard to do?

**Comment by jilliangmeehan** [comment]
not hard to do, there are just other things i want to focus on before i do this i think. but we can definitely do this.

**Comment by jilliangmeehan** [comment]
for each one, will you only want to have an award line, directed by, and agency? or will it be more variable?

**Comment by jilliangmeehan** [comment]
bc if it's just those 3 things generally the easiest way to do it would be to have like a "directed by" and "agency" line for each project in the data file. if they don't have one we just don't put it for that project.

**Comment by dylanjedwards** [comment]
It *might* be more variable, but generally it would be

(Potential) Award Line
Director
Agency
Production Company

**Comment by jilliangmeehan** [comment]
ok well not now but at some point when i start working on this what you can do is go through the projects and figure out what it'll be for each one

**Comment by dylanjedwards** [comment]
should I do that on that original doc I did? or somewhere else

**Comment by jilliangmeehan** [comment]
in the data file is where we'll need it, but you don't have to worry about it yet
