### ISSUE TITLE
category dropdown enhancements

### ISSUE THREAD

**Issue by dylanjedwards** [jilliangmeehan/dylan-edwards#28]
would be perfect if we can have the selected category displayed above the drop down, and the drop down would change that display

currently it's not super clear how to access categories

### specs
- [x] smoother dropdown animation
- [ ] display current category to the left of the "+" button
- [x] animate categories when you hover over them

**Comment by jilliangmeehan** [comment]
@dylanjedwards do you want the dropdown to automatically close or stay open until you click the button again when you pick a new category?

**Comment by dylanjedwards** [comment]
stay open I think
