### ISSUE TITLE
add social icons

### ISSUE THREAD

**Issue by jilliangmeehan** [jilliangmeehan/dylan-edwards#6]
# specs
add icons to bottom right corner:
* instagram: opens instagram in new tab
* vimeo: opens vimeo in new tab
* email: scrolls down to contact section
* [bedroom editorial](https://drive.google.com/open?id=1Xf5Ypc2gpDfbMrbLxRKG2zGwuIY0qyBF): opens bedroom website in new tab

icons should have higher z-index than project titles :)

# design
tbd!

**Comment by jilliangmeehan** [comment]
@dylanjedwards i think having the bedroom logo here would be quite quite tiny and wouldn't really retain enough detail to look great + having a multi-colored logo next to some more uniform white icons seems slightly off. what if we put it next to your name in the header?

**Comment by dylanjedwards** [comment]
I feel like it'll have too much prominence up there, can we just try and see and then evaluate if it needs to be black+white or removed altogether?

**Comment by jilliangmeehan** [comment]
ok i just pushed it so you can see what it looks like
